### ISSUE TITLE
Any plans to support running on top of XWayland?

### ISSUE THREAD

**Issue by karolherbst** [amonakov/primus#143]
I've played a bit around with XWayland and got bumblebee running through vgl without big problems (some window issues, but nothing dramatic).

Are there any plans to support primus on top of XWayland? Should I investigate some time into debugging errors I find?

**Comment by sjnewbury** [comment]
I don't suppose it would be possible to load the nvidia driver directly into an Xwayland xserver?  It seems excessive to go: nvidia-X-server -> Xwayland xserver -> wl_surface

What I'm suggesting is a second Xwayland server using the nvidia driver instead of the glamor ddx.  Originally the Xwayland server used the normal xorg ddx drivers so it should be possible...?
