### ISSUE TITLE
steam games failing after latest update

### ISSUE THREAD

**Issue by cjano** [amonakov/primus#63]
following error on all steam games after latest primus update  ( this veekend )

Game update: AppID 440 "Team Fortress 2", ProcID 5095, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Segmentation fault (core dumped)
Game removed: AppID 440 "Team Fortress 2", ProcID 5095 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

there was also a steam client update so not sure what causing this issue
i\m running on 12.04 64bit

**Comment by drydenp** [comment]
Do these issues happen more frequently? This was years ago but presently I have a Intel G45 + regular Steam (downloaded March 2015) (just yesterday) that will not load any game (I presume) because those overlay libs are not being loaded. Same error. Mostly the same. Nothing to do with Primus then, but Steam seems to do this thing a lot.
